#!/bin/bash

# debootstrap bookworm . http://deb.debian.org/debian
# chroot .
# apt install --no-install-recommends fish git ca-certificates ncurses-term sudo ranger
# useradd ptixed
# passwd ptixed
# usermod -aG sudo ptixed

if [ $(whoami) != root ]; then
    sudo "$0"
    exit
fi

cd "$(dirname "$0")"

if ! mountpoint -q proc; then
    mount -t proc /proc proc/
    mount -t sysfs /sys sys/
    mount --rbind /dev dev/
fi

chroot --userspec=ptixed . /usr/bin/env -i HOME=/home/ptixed TERM=$TERM fish --init-command=cd

