#!/usr/bin/fish

set zones 'Europe/Warsaw' 'America/New_York' 'America/Chicago' 'UTC'
set names '' ' ET' ' CT' ' UTC'
set total (count $zones)
set now (date +%s)

switch $argv[1]
    case init
        set zone 1
    case refresh
        TZ=$zones[$zone] set output (date "+%b"; LANG=ja_JP.UTF-8 date "+%d %a %H:%M$names[$zone]")
    case scrollup
        set zone (math "$zone % $total + 1")
    case scrolldown
        set zone (math "($zone - 2 + $total) % $total + 1")
end

echo zone=$zone
echo wake=(math "floor($now/60)*60+60")
echo output=(echo $output | string escape)
