#!/usr/bin/fish

switch $argv[1]
    case refresh
        set output (string match -r '\d+%' (pactl get-source-volume @DEFAULT_SOURCE@))
        if string match -q "Mute: no" (pactl get-source-mute @DEFAULT_SOURCE@)
            set output " $output"
        else
            set output " $output"
        end
    case scrollup
        pactl set-source-volume @DEFAULT_SOURCE@ +5%
    case scrolldown
        pactl set-source-volume @DEFAULT_SOURCE@ -5%
    case lmb
        pactl set-source-mute @DEFAULT_SOURCE@ toggle
    case rmb
        pavucontrol &
end

echo output=(echo $output | string escape)
