#!/usr/bin/fish

switch $argv[1]
    case refresh
        set volume (wpctl get-volume @DEFAULT_SOURCE@)
        set output (echo "$volume" | sed -E -e 's/.*([0-9])\.([0-9][0-9]).*/\1\2%/' -e 's/^0//g')
        if test "$volume" = "*MUTED*"
            set output " $output"
        else
            set output " $output"
        end
    case scrollup
        wpctl set-volume @DEFAULT_SOURCE@ 0.05+
    case scrolldown
        wpctl set-volume @DEFAULT_SOURCE@ 0.05-
    case lmb
        # TODO click to switch between A2 and HF
        # do not show mic when not present
end

echo output=(echo $output | string escape)
