#!/usr/bin/fish

switch $argv[1]
    case refresh
        set volume (wpctl get-volume @DEFAULT_SINK@)
        set output (echo "$volume" | sed -E -e 's/.*([0-9])\.([0-9][0-9]).*/\1\2%/' -e 's/^0//g')
        if test "$volume" = "*MUTED*"
            set output " $output"
        else
            set output " $output"
        end
    case scrollup
        wpctl set-volume @DEFAULT_SINK@ 0.05+
        kill (cat pid)
    case scrolldown
        wpctl set-volume @DEFAULT_SINK@ 0.05-
        kill (cat pid)
end

echo output=(echo $output | string escape)
