#!/usr/bin/fish

switch $argv[1]
    case refresh
        set output (string match -r '\d+%' (pactl get-sink-volume @DEFAULT_SINK@))
        if string match -q "Mute: no" (pactl get-sink-mute @DEFAULT_SINK@)
            set output " $output"
        else
            set output " $output"
        end
    case scrollup
        pactl set-sink-volume @DEFAULT_SINK@ +5%
    case scrolldown
        pactl set-sink-volume @DEFAULT_SINK@ -5%
    case lmb
        pactl set-sink-mute @DEFAULT_SINK@ toggle
end

echo output=(echo $output | string escape)
