version: '3'

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - '0.0.0.0:53:53/tcp'
      - '0.0.0.0:53:53/udp'
      - '0.0.0.0:8053:80/tcp'
    environment:
      TZ: 'Europe/Warsaw'
    volumes:
      - './etc/pihole:/etc/pihole'
      - './etc/dnsmasq.d:/etc/dnsmasq.d'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
